name: Build for WebGL and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions/setup-rust@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-name game \
          --out-dir target \
          --target web target/wasm32-unknown-unknown/release/try-rust-bevy.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git switch gh-pages
          git add target/game.js
          git add target/game_bg.wasm
          git commit -m "build"
          git push -f origin main:gh-pages
