name: Build for WebGL and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Rust
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install wasm-bindgen-cli --version 0.2.88
          cargo update -p wasm-bindgen --precise 0.2.88

      - name: Build
        run: |
          cargo build --release --target wasm32-unknown-unknown
          wasm-bindgen --out-name game \
            --out-dir target \
            --target web target/wasm32-unknown-unknown/release/try-rust-bevy.wasm

      - name: Move Files
        run: |
          mkdir tmp
          mv target/game.js tmp/game.js
          mv target/game_bg.wasm tmp/game_bg.wasm

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup
        run: |
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git config --global user.name ${{ secrets.USER_NAME }}
          git fetch
          git switch gh-pages

      - name: Deploy to GitHub Pages
        run: |
          mv tmp/game.js target/game.js
          mv tmp/game_bg.wasm target/game_bg.wasm
          git add target/game.js
          git add target/game_bg.wasm
          git commit -m "build"
          git push -f origin main:gh-pages
